apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-stateless-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-stateless-app
  template:
    metadata:
      labels:
        app: my-stateless-app
    spec:
      containers:
      - name: my-app-container
        image: your_image:latest
        ports:
        - containerPort: 80

